/***


ALL PERFECT VISION SOURCE FILES ARE COPYRIGHTED 1988 BY SUNRIZE INDUSTRIES
AND MAY NOT BE DISTRIBUTED IN ANY WAY.  ANYONE GIVEN ACCESS TO THE PERFECT
VISION SOURCE FILES IS PROHIBITED FROM MAKING COPIES EXCEPT FOR BACKUP
PURPOSES.


****/

