//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by GENERIC.RC
//
#define IDM_ABOUT                       100
#define IDM_OPTIONS                     101
#define IDI_MAZE                        102
#define IDM_NEW                         102
#define IDD_OPTIONS                     103
#define IDM_EXIT                        103
#define IDM_PRINT                       104
#define IDC_HCELLSIZE                   1000
#define IDC_VCELLSIZE                   1001
#define IDC_SPEED                       1002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         105
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
