#pragma libcall SoundSwitchBase ssw_RexxHost 1E 801
#pragma libcall SoundSwitchBase ssw_LockBase 24 0
#pragma libcall SoundSwitchBase ssw_AttemptLockBase 2A 0
#pragma libcall SoundSwitchBase ssw_UnlockBase 30 0
#pragma libcall SoundSwitchBase ssw_ObtainHardware 36 0
#pragma libcall SoundSwitchBase ssw_ReleaseHardware 3C 0
#pragma libcall SoundSwitchBase ssw_OpenUnit 42 81003
#pragma libcall SoundSwitchBase ssw_CloseUnit 48 801
#pragma libcall SoundSwitchBase ssw_TestUnit 4E 801
#pragma libcall SoundSwitchBase ssw_GetUnitInfo 54 9802
#pragma libcall SoundSwitchBase ssw_AddMonitor 5A A109805
#pragma libcall SoundSwitchBase ssw_RemoveMonitor 60 801
#pragma libcall SoundSwitchBase ssw_SetMode 66 10803
#pragma libcall SoundSwitchBase ssw_SetChannelGain 6C 10803
#pragma libcall SoundSwitchBase ssw_GetChannelGain 72 0802
#pragma libcall SoundSwitchBase ssw_SetChannelTrim 78 10803
#pragma libcall SoundSwitchBase ssw_GetChannelTrim 7E 0802
#pragma libcall SoundSwitchBase ssw_GetMeterInfo 84 0802
