
#ifndef HARDWARE_INTBITS_H
#define HARDWARE_INTBITS_H
#define  INTB_SETCLR    (15)
#define  INTB_INTEN     (14)
#define  INTB_EXTER     (13)
#define  INTB_DSKSYNC   (12)
#define  INTB_RBF       (11)
#define  INTB_AUD3      (10)
#define  INTB_AUD2      (9)
#define  INTB_AUD1      (8)
#define  INTB_AUD0      (7)
#define  INTB_BLIT      (6)
#define  INTB_VERTB     (5)
#define  INTB_COPER     (4)
#define  INTB_PORTS     (3)
#define  INTB_SOFTINT   (2)
#define  INTB_DSKBLK    (1)
#define  INTB_TBE       (0)
#define  INTF_SETCLR    (1<<15)
#define  INTF_INTEN     (1<<14)
#define  INTF_EXTER     (1<<13)
#define  INTF_DSKSYNC   (1<<12)
#define  INTF_RBF       (1<<11)
#define  INTF_AUD3      (1<<10)
#define  INTF_AUD2      (1<<9)
#define  INTF_AUD1      (1<<8)
#define  INTF_AUD0      (1<<7)
#define  INTF_BLIT      (1<<6)
#define  INTF_VERTB     (1<<5)
#define  INTF_COPER     (1<<4)
#define  INTF_PORTS     (1<<3)
#define  INTF_SOFTINT   (1<<2)
#define  INTF_DSKBLK    (1<<1)
#define  INTF_TBE       (1<<0)
#endif !HARDWARE_INTBITS_H
